---
- name: Install a Ray head node or worker
  hosts: all
  vars:
    ray_head_node: false
    ray_worker_node: not ray_head_node
    ray_head_node_address: "" # if this is a worker node, what head node should we connect to?
    ray_head_node_command: |
    ray_dashboard_port: "8265"
    ray_client_server_port: "10001"
    ray_head_port: "6379"
    ray_env: {}
    gather_facts: false

  tasks:

    - name: Create user ray # fill in

    - name: Find private network interface # fill in -- assume there is only one private network interface
      # attempt to make this task as generic as possible so it works across linux/unix flavours, but if necessary, just assume Debian or Ubuntu
      # register the result in the variable _private_network

    - name: Set ray command (head node) # complete
      when: ray_head_none
      ansible.builtin.set_fact:
        _ray_cmd: uv run ray start --head --node-ip-address={{ _private_network }} --port={{ ray_head_port }} --dashboard-host={{ __private_network }} --dashboard-port={{ ray_dashboard_port }} --ray-client-server-port={{ ray_client_server_port }}

    - name: Set ray command (worker node) # complete
      when: ray_worker_node
      ansible.builtin.set_fact:
        _ray_cmd: uv run ray start --address="{{ ray_head_node_address }}:{{ ray_head_port }}" --node-ip-address="{{ _private_network }}"

    - name: Create Ray systemd service # fill in
      # run as user ray
      # run command _ray_cmd
      # allow passing optional extra environment variables defined in variable ray_env
      # run handler

    - name: Start Ray systemd service # fill in -- this should be a handler
