---
- name: Install a Ray head node or worker
  hosts: all
  vars:
    _ray_head_node: "{{ ray_head_node | default(false, true) | bool }}"
    _ray_head_node_address: "{{ ray_head_node_address | default('', true) }}"
    _ray_dashboard_port: "{{ ray_dashboard_port | default('8265', true) }}"
    _ray_client_server_port: "{{ ray_client_server_port | default('10001', true) }}"
    _ray_head_node_port: "{{ ray_head_node_port | default('6379', true) }}"
    _ray_env: "{{ ray_env | default('') }}"
    _ray_public_key: "{{ ray_public_key | default('') }}"
    _ray_fail_hard: "{{ ray_fail_hard | default(false, true) | bool }}"
    _ray_default_packages:
      - default
      - client
    _ray_user_packages: "{{ ray_packages | default('') }}"
    _ray_packages: >-
      {%- if (_ray_user_packages | length) > 0 -%}
      [{{ _ray_user_packages }}]
      {%- else -%}
      [{{ _ray_default_packages | join(',') }}]
      {%- endif -%}
    _ray_python_version: "{{ ray_python_version | default('') }}"
    _ray_setup: true # in the future make this optional, in case `ray up` wants to install ray itself
    _ray_service_name: "ray_{{ _ray_head_node | ternary('head', 'worker') }}"
    _ray_venv: /opt/{{ _ray_service_name }}-venv
    _ray_cmd: "{{ _ray_venv }}/bin/ray"
    gather_facts: false

  tasks:
    - name: User provisioning
      block:
        - name: Create user ray
          ansible.builtin.user:
            name: ray
            state: present

        - name: Setup ssh key
          when: (_ray_public_key | length) > 0
          ansible.posix.authorized_key:
            user: ray
            state: present
            key: "{{ _ray_public_key }}"

        - name: Allow ray user to control systemd service
          tags: molecule-idempotence-notest
          community.general.sudoers:
            name: ray-systemctl
            state: present
            user: ray
            nopassword: true
            commands:
              - /usr/bin/systemctl start {{ _ray_service_name}}.service
              - /usr/bin/systemctl restart {{ _ray_service_name}}.service
              - /usr/bin/systemctl stop {{ _ray_service_name}}.service

    - name: Find private network
      block:
        - name: Create find_ip script
          ansible.builtin.copy:
            src: find_private_ip.sh
            dest: /usr/local/bin/find_private_ip.sh
            owner: root
            group: root
            mode: "0655"

        - name: Test find private ip
          ansible.builtin.command:
            cmd: /usr/local/bin/find_private_ip.sh
          register: find_private_ip
          changed_when: false

        - name: Fail if no private network
          when:
            - find_private_ip.rc != 0
          ansible.builtin.fail:
            msg: "No private network found! Result of script: {{ find_private_ip.stdout }}"

        - name: Set internal ip
          ansible.builtin.set_fact:
            _ray_internal_ip: "{{ find_private_ip.stdout | trim }}"

        - name: Set connect address
          ansible.builtin.set_fact:
            _ray_connect_address: >-
              {%- if _ray_head_node_address | length > 0 -%}
              {%- if ':' in _ray_head_node_address -%}
              {{ _ray_head_node_address }}
              {%- else -%}
              {{ _ray_head_node_address }}:{{ _ray_head_node_port }}
              {%- endif -%}
              {%- elif _ray_head_node -%}
              {{ _ray_internal_ip }}:{{ _ray_head_node_port }}
              {%- endif -%}

        - name: Create Ray env file
          ansible.builtin.template:
            src: ray.env.j2
            dest: "/home/ray/{{ _ray_service_name }}.env"
            owner: ray
            group: ray
            mode: "0600"

    - name: Setup Ray
      when: _ray_setup
      block:
        - name: Create venv
          ansible.builtin.command:
            cmd: |-
              uv venv
              {% if (_ray_python_version | length) > 0 %}
              --python {{ _ray_python_version }}
              {% else %}
              --no-managed-python
              {% endif %}
              {{ _ray_venv }}
            creates: "{{ _ray_venv }}"
          environment:
            UV_PYTHON_INSTALL_DIR: /opt/

        - name: Install ray
          ansible.builtin.command:
            cmd: uv pip install ray{{ _ray_packages }}
            creates: "{{ _ray_venv }}/bin/ray"
          environment:
            VIRTUAL_ENV: "{{ _ray_venv }}"

        - name: Create Ray systemd service
          ansible.builtin.template:
            src: ray.service.j2
            dest: /etc/systemd/system/{{ _ray_service_name }}.service
            owner: root
            group: root
            mode: "0644"
          notify:
            - Start ray systemd service
            - Fail if ray is not active

  handlers:

    - name: Start ray systemd service
      ansible.builtin.systemd:
        name: "{{ _ray_service_name }}"
        state: restarted
        enabled: true
        daemon_reload: true

    - name: Fail if ray is not active
      when: _ray_fail_hard
      ansible.builtin.command: sudo -uray {{ _ray_cmd }} status --address "{{ _ray_connect_address }}"
      register: ray_status
      failed_when: "not 'Active' in ray_status.stdout"
      changed_when: false
      retries: 6
      delay: 1 # the status command itself retries for 5 seconds
