---
- name: Install a Ray head node or worker
  hosts: all
  vars:
    _ray_head_node: "{{ ray_head_node | default(false, true) | bool }}"
    _ray_head_node_address: "{{ ray_head_node_address | default('', true) }}"
    _ray_dashboard_port: "{{ ray_dashboard_port | default('8265', true) }}"
    _ray_client_server_port: "{{ ray_client_server_port | default('10001', true) }}"
    _ray_head_node_port: "{{ ray_head_node_port | default('6379', true) }}"
    _ray_env: "{{ ray_env | default('') }}"
    _ray_public_key: "{{ ray_public_key | default('') }}"
    gather_facts: false

  tasks:

    # todo add storage location
    # todo scan for head node?

    - name: Create user ray
      ansible.builtin.user:
        name: ray
        state: present

    - name: Setup ssh key
      when: (_ray_public_key | length) > 0
      ansible.posix.authorized_key:
        user: ray
        state: present
        key: "{{ _ray_public_key }}"

    - name: Allow ray user to control systemd service
      community.general.sudoers:
        name: ray-systemctl
        state: present
        user: ray
        nopassword: true
        commands:
          - /usr/bin/systemctl start ray.service
          - /usr/bin/systemctl restart ray.service
          - /usr/bin/systemctl stop ray.service

    - name: Install ray
      become: true
      become_user: ray
      ansible.builtin.command: uv tool install "ray[default]"

    - name: Create find_ip script
      ansible.builtin.copy:
        src: find_private_network.sh
        dest: /usr/local/bin/find_private_network.sh
        owner: root
        group: root
        mode: "0655"

    - name: Create start_ray script
      ansible.builtin.template:
        src: start_ray.sh.j2
        dest: /usr/local/bin/start_ray.sh
        owner: root
        group: root
        mode: "0655"

    - name: Test find network interface
      ansible.builtin.command:
        cmd: /usr/local/bin/find_private_network.sh
      register: find_private_network

    - name: Fail if no private network
      when: find_private_network.rc != 0
      ansible.builtin.fail:
        msg: "No private network found! Result of script: {{ find_private_network.stdout }}"

    - name: Create Ray systemd service
      ansible.builtin.template:
        src: ray.service.j2
        dest: /etc/systemd/system/ray.service
        owner: ray
        group: ray
        mode: "0644"
      notify:
        - Start Ray systemd service
        - Fail if ray is not active

    - name: Enable logrotation
      ansible.builtin.blockinfile:
        path: /etc/logrotate.d/ray
        block: >
          /var/log/ray/ {
            hourly
            rotate 5
            size 50M
            compress
            delaycompress
            missingok
            copytruncate
          }
        create: true
        mode: "0644"

  handlers:

    - name: Start Ray systemd service
      ansible.builtin.systemd:
        name: ray
        state: started
        daemon_reload: true

    - name: Fail if ray is not active
      become: true
      become_user: ray
      ansible.builtin.command: uv tool run ray status
      retries: 10
      delay: 5
