---
driver:
  name: ${DRIVER-podman}
platforms:
  - name: test-ray
    image: ghcr.io/utrechtuniversity/src-test-workspace:ubuntu_noble
    command: /sbin/init
    pre_build_image: true
    published_ports:
      - 10001:10001
      - 6379:6379
      - 8265:8265
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
